# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reranker.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'reranker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ereranker.proto\x12\x16\x61gentformc.reranker.v1\"\x0f\n\rHealthRequest\"D\n\x0eHealthResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"B\n\x0eRerankDocument\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x13\n\x0b\x64ocument_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"|\n\rRerankRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x39\n\tdocuments\x18\x03 \x03(\x0b\x32&.agentformc.reranker.v1.RerankDocument\x12\r\n\x05top_k\x18\x04 \x01(\x05\"C\n\x0eRankedDocument\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x13\n\x0b\x64ocument_id\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x01\"]\n\x0eRerankResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x37\n\x07results\x18\x02 \x03(\x0b\x32&.agentformc.reranker.v1.RankedDocument2\xc3\x01\n\x0fRerankerService\x12W\n\x06Health\x12%.agentformc.reranker.v1.HealthRequest\x1a&.agentformc.reranker.v1.HealthResponse\x12W\n\x06Rerank\x12%.agentformc.reranker.v1.RerankRequest\x1a&.agentformc.reranker.v1.RerankResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reranker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=42
  _globals['_HEALTHREQUEST']._serialized_end=57
  _globals['_HEALTHRESPONSE']._serialized_start=59
  _globals['_HEALTHRESPONSE']._serialized_end=127
  _globals['_RERANKDOCUMENT']._serialized_start=129
  _globals['_RERANKDOCUMENT']._serialized_end=195
  _globals['_RERANKREQUEST']._serialized_start=197
  _globals['_RERANKREQUEST']._serialized_end=321
  _globals['_RANKEDDOCUMENT']._serialized_start=323
  _globals['_RANKEDDOCUMENT']._serialized_end=390
  _globals['_RERANKRESPONSE']._serialized_start=392
  _globals['_RERANKRESPONSE']._serialized_end=485
  _globals['_RERANKERSERVICE']._serialized_start=488
  _globals['_RERANKERSERVICE']._serialized_end=683
# @@protoc_insertion_point(module_scope)
